### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by NodexTech** [senthilporunan/atom-cubic-bezier#14]
[Enter steps to reproduce below:]

1. Install it
2. Wait for the error

**Atom Version**: 1.0.4
**System**: Mac OS X 10.10.4
**Thrown From**: [cubic-bezier](https://github.com/senthilporunan/atom-cubic-bezier) package, v1.4.0

### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /Users/nodex/.atom/packages/cubic-bezier/lib/cubic-bezier-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/nodex/.atom/packages/cubic-bezier/lib/cubic-bezier-view.coffee:1:1)
  at /Users/nodex/.atom/packages/cubic-bezier/lib/cubic-bezier-view.coffee:8:3
  at Object.<anonymous> (/Users/nodex/.atom/packages/cubic-bezier/lib/cubic-bezier-view.coffee:124:5)
  at Object.<anonymous> (/Users/nodex/.atom/packages/cubic-bezier/lib/cubic-bezier-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/nodex/.atom/packages/cubic-bezier/lib/cubic-bezier.coffee:1:19)
  at Object.<anonymous> (/Users/nodex/.atom/packages/cubic-bezier/lib/cubic-bezier.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:759:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:261:14)
  at PackageDetailView.module.exports.PackageDetailView.activate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:150:26)
  at PackageDetailView.module.exports.PackageDetailView.updateInstalledState (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:187:12)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:232:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:587:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:378:26
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -2:23.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:12.7.0 core:paste (atom-text-editor.editor.is-focused)
     -2:08.6.0 core:select-all (atom-text-editor.editor.is-focused)
     -2:08.1.0 core:copy (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ],
    "disabledPackages": [
      "project-manager",
      "remote-edit",
      "atom-ftp-editor",
      "remote-sync",
      "linter-phpmd"
    ],
    "projectHome": "/Volumes/External4TB/Work"
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.7.1
aligner-css, v1.2.0
aligner-php, v1.0.0
autocomplete-php, v0.3.6
cssbeautify, v1.1.0
less-than-slash, v0.7.0
linter, v1.3.1
linter-php, v1.0.3
php-analyser, v0.2.0
php-introspector, v1.0.0
php-twig, v4.0.0

# Dev
No dev packages
```

**Comment by Chrisedmo** [comment]
I'm getting the same :-(

**Comment by senthilporunan** [comment]
As atom editor upgraded their version, we need make some changes in our plugin also. Tomorrow, we will work on this one and fix this ASAP.

**Comment by senthilporunan** [comment]
Issue fixed. From version v2.0 onwards, its working fine.
