### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by entepe85** [senthilporunan/atom-cubic-bezier#15]
[Enter steps to reproduce below:]

1. Open Command Palette
2. Try opening the cubic bezier editor from there

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.5
**Thrown From**: [cubic-bezier](https://github.com/senthilporunan/atom-cubic-bezier) package, v1.5.16

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/nils/.atom/packages/cubic-bezier/lib/cubic-bezier-curve.coffee:279

TypeError: undefined is not a function
  at CubicBezierCurve.module.exports.CubicBezierCurve.selectMatches (/Users/nils/.atom/packages/cubic-bezier/lib/cubic-bezier-curve.coffee:279:27)
  at CubicBezierCurve.module.exports.CubicBezierCurve.showCubicBezier (/Users/nils/.atom/packages/cubic-bezier/lib/cubic-bezier-curve.coffee:75:4)
  at CubicBezierView.module.exports.CubicBezierView.toggle (/Users/nils/.atom/packages/cubic-bezier/lib/cubic-bezier-view.coffee:55:20)
  at atom-workspace.atom.commands.add.cubic-bezier:open (/Users/nils/.atom/packages/cubic-bezier/lib/cubic-bezier-view.coffee:36:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -0:06.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.9.0 cubic-bezier:open (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".DS_Store",
      ".git",
      ".svn"
    ],
    "disabledPackages": [
      "feedback",
      "metrics",
      "styleguide",
      "welcome",
      "snippets",
      "package-generator",
      "dev-live-reload",
      "linter-jshint",
      "emmet",
      "htmlhint",
      "deprecation-cop",
      "jekyll",
      "atom-color-highlight",
      "git-tab-status"
    ],
    "projectHome": "/Users/nils/Desktop/Work/",
    "themes": [
      "one-dark-ui",
      "chester-atom-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-minify, v0.2.2
autoclose-html, v0.18.0
autocomplete-php, v0.3.6
bezier-curve-editor, v0.7.2
chester-atom-syntax, v0.1.1
color-picker, v2.0.11
cubic-bezier, v1.5.16
file-icons, v1.6.6
fold-functions, v0.3.1
git-log, v0.4.1
grammar-token-limit, v0.1.1
highlight-selected, v0.10.1
jslint, v1.4.0
language-htaccess, v0.1.1
less-autocompile, v1.0.0
minimap, v4.12.3
minimap-find-and-replace, v4.3.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.0
minimap-pigments, v0.1.5
pigments, v0.11.0
project-manager, v1.15.11
sass-autocompile, v0.7.5
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by senthilporunan** [comment]
Issue fixed. From version v2.0 onwards, its working fine.
